use_frameworks!

platform :ios, '9.0'

target 'MKLoRaWAN-MP_Example' do
  pod 'MKLoRaWAN-MP', :path => '../'

  target 'MKLoRaWAN-MP_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
